config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'home/resume' => 'home#resume'

  resource :gdangers do
      resources :posts
  end

  resources :categories do
    resources :posts
  end

  resources :tags do
    resources :posts,  only: [:index, :show]
  end



end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  belongs_to :categories
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @posts = Post.where(category_id: params[:id])
  end

end

app/controllers/gdangers_controller.rb
class GdangersController < ApplicationController

  def show
    if params[:edit_passcode] == "pennypeaches"
      @login_allowed = true
      @posts = Post.all
    else
      @login_allowed = false
    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @title = "Lauren Granger"
    @posts = Post.all
  end

  def new
    # write_password = params[:write_passcode]
    # edit_password = params[:edit_passcode]
    # if write_password == "pennypeaches"
    #   @login_allowed = true
    #   redirect_to new_home_post_path
    # elsif edit_password == "peachespenny"
    #   redirect_to edit_home_post_path
    # else
    #   @login_allowed = false
    #   redirect_to 'root'
    # end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @login_allowed = true
    @post = Post.new
    @categories = Category.all
    @tags = Tag.all
    @action = "create"
  end

  def create
    new_post = Post.create(post_params)
    new_post.update(content: params[:content], category_id: params[:category_id], pub_dat: Time.now, :tags => Tag.where(:id => params[:tags]))
    redirect_to "/gdangers"
  end

  def edit
    @login_allowed = true
    @post = Post.find(params[:id])
    @categories = Category.all
    @tags = Tag.all
    @action = "update"
  end

  def update
    update_post = Post.find(params[:id])
    update_post.update(content: params[:content], category_id: params[:category_id], pub_dat: Time.now, :tags => Tag.where(:id => params[:tags]))
    redirect_to "/gdangers"
  end

  def show
    @post = Post.find(params[:id])
    @title = @post.title
  end

  private

  def post_params
    params.require(:post).permit([:title])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gdangers_helper.rb
module GdangersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/show.html.erb
<div class="main_content">

<% @posts.each do |post| %>

<% @category = Category.find(post.category_id).name %>
<% @tags = post.tags.map {|t| t.name} %>
<% @date = post.pub_dat %>

  <h3><a href="/categories/<%= post.category_id %>/posts/<%= post.id %>">
    <%= post.title %>:
    <em><%= @category %>
    <% @tags.each do |t|  %>
      <%= " ##{t}" %>
    <% end %>
    <%= @date.month %>/<%= @date.day %>/<%= @date.year %></em>
   </a></h3>
<br>
<% end %>
</div>

app/views/gdangers/new.html.erb
<%# This is the login page to the create and edit posts %>
<%# Links to page showing all posts avaliable to edit => GET  ||  /gdangers(.:format)  ||  gdangers#show %>

<h1>Hello Lauren!</h1>
<h2>let's make some blog posts</h2>

<form id="for_lauren" action="/gdangers" method="get">

  <input type="password" name="edit_passcode">
  <br>
  <input form="for_lauren" type="submit" name="to_edit" id="to_edit" value="edit page">

</form>

app/views/gdangers/show.html.erb
<%# Shows all posts avaliable to edit %>
<%# Links to edit page for a given post => edit_gdangers_post GET  ||  /gdangers/posts/:id/edit(.:format)  ||  posts#edit %>
<%# Link to create a new post => new_gdangers_post GET  ||  /gdangers/posts/new(.:format)  ||  posts#new %>

<% if @login_allowed == true %>
  <%= link_to 'New Post', new_gdangers_post_path %>
  <% @posts.each do |post| %>
    <h3>
      <a href="/gdangers/posts/<%= post.id %>/edit">
      <%= post.title %>: date = <%= post.pub_dat.month %>/<%= post.pub_dat.year %></a>
    </h3>
  <% end %>
<% else %>
  <h3>
  You are not Lauren. Go away.
  </h3>
<% end %>

app/views/home/index.html.erb
<%# This is the home page of the site. It shows post preveiws in a square grid. %>
<%# Links to individual posts =>  category_post GET  ||  /categories/:category_id/posts/:id(.:format)  ||  posts#show%>

<div class="main_content">

<% @posts.each do |post| %>

<% @category = Category.find(post.category_id).name %>
<% @tags = post.tags.map {|t| t.name} %>
<% @date = post.pub_dat %>

  <h3><a href="/categories/<%= post.category_id %>/posts/<%= post.id %>">
    <%= post.title %>:
    <em><%= @category %>
    <% @tags.each do |t|  %>
      <%= " ##{t}" %>
    <% end %>
    <%= @date.month %>/<%= @date.day %>/<%= @date.year %></em>
   </a></h3>
<br>
<% end %>
</div>

app/views/home/resume.html.erb
<%# This page will show my resume %>

app/views/layouts/application.html.erb
<%# Navigation links to: %>
  <%# home/ %>
  <%# home/resume %>
  <%# category GET  ||  /categories/:id(.:format)  ||  categories#show %>
<%# Links to login page => new_gdangers GET  ||  //gdangers/new(.:format)  ||  /gdangers#new %>

<!DOCTYPE html>
<html>

<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag 'application.scss' %>
  <link href="laurengranger.ico" rel="shortcut icon" type="image/png">
</head>

<header>
  <h1><%= @title %></h1>
  <nav>
    <a href="/">home</a>
    <%= link_to "code", category_path(1) %>
    <%= link_to "social justice", category_path(2) %>
    <%= link_to "outside", category_path(3) %>
    <%= link_to "food", category_path(4) %>
    <%= link_to "projects", category_path(5) %>
    <%= link_to "other", category_path(6) %>

  </nav>
</header>

<body class="main">
  <%= yield %>
</body>

<footer>
  <%= "Lauren Granger" %> <a href="/gdangers/new">|</a> <%= "copyright #{Time.now.year}" %>
</footer>

</html>

app/views/posts/_form.html.erb
<% if @login_allowed == true %>

  <%= form_for @post, url: {action: @action} do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <br>
    <%= f.label :content %>
    <%= text_area_tag(:content, @post.content, size: "200x30") %>

    <fieldset>
      <legend>Categories</legend>

      <% @categories.each do |cat| %>
        <% if @post.category_id == cat.id %>
          <%= radio_button_tag(:category_id, "#{cat.id}", :checked)%>
          <%= label_tag(:category_id, "#{cat.name}") %>
        <% else %>
          <%= radio_button_tag(:category_id, "#{cat.id}")%>
          <%= label_tag(:category_id, "#{cat.name}") %>
        <% end %>
      <% end %>

    </fieldset>

    <fieldset>
      <legend>Tags</legend>
      <% tag_ids = @post.tags.map {|n| n.id} %>
        <% @tags.each do |tag| %>
          <% if tag_ids.include?(tag.id) %>
            <%= check_box_tag "tags[]", "#{tag.id}", :checked %>
            <%= label_tag "tags[]", "#{tag.name}" %>
          <% else %>
            <%= check_box_tag "tags[]", "#{tag.id}" %>
            <%= label_tag "tags[]", "#{tag.name}" %>
          <% end %>
        <% end %>


    </fieldset>
    <%= f.submit 'submit' %>
    <% end %>

<% else %>
  <h3>
  You are not Lauren. Go away.
  </h3>
<% end %>

app/views/posts/edit.html.erb
<%# Form for editing a given post %>
<%# Goes to controller => PATCH  ||  /gdangers/posts/:id(.:format)  ||  posts#update %>
<%# update routes back to page showing all posts avaliable to edit => GET  ||  /gdangers(.:format)  ||  gdangers#show %>
<%= render 'form' %>

app/views/posts/new.html.erb
<%# Form for creating a new post %>
<%# routes to POST  ||  /gdangers/posts(.:format)  ||  posts#create%>
<%# create routes back to page showing all posts avaliable to edit => GET  ||  /gdangers(.:format)  ||  gdangers#show %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%# Displays the page of a given post %>
<%# links back to home and to catagorys are handled by the applicaiton layout %>
<div class="main_content">

<h3><%= @post.content %></h3>
<h2>
  -Lauren
  <% @date = @post.pub_dat %>
  <%= @date.month %>/<%= @date.day %>/<%= @date.year %>
</h2>
<p>
  <%= Category.find(@post.category_id).name %>
  <% @tags = @post.tags.map {|t| t.name} %>
  <% @tags.each do |t|  %>
    <%= " ##{t}" %>
  <% end %>
</p>

</div>